name: "Setup gh cli"
description: "Setup gh cli in self-hosted runners. This action is to setup gh cli in self-hosted runners"
author: "ksivamuthu"
inputs:
  version:
    required: false
    description: 'gh cli version to download'
  platform:
    required: false
    description: 'gh cli binary platform to download'
  arch:
    required: false
    description: 'Architecture of the gh cli binary to download (amd64 or arm64). If not specified, the system architecture is automatically detected.'
runs:
  using: 'node16'
  main: 'dist/index.js'
